In [21]:
#https://github.com/nghiaho12/rigid_transform_3D

from numpy import *
from math import sqrt

# Input: expects 3xN matrix of points
# Returns R,t
# R = 3x3 rotation matrix
# t = 3x1 column vector

def rigid_transform_3D(A, B):
    assert len(A) == len(B)

    num_rows, num_cols = A.shape;

    if num_cols != 2:
        raise Exception("matrix A is not Nx2, it is {}x{}".format(num_rows, num_cols))

    [num_rows, num_cols] = B.shape;
    if num_cols != 2:
        raise Exception("matrix B is not Nx2, it is {}x{}".format(num_rows, num_cols))

    # find mean column wise
    centroid_A = mean(A, axis=0)
    centroid_B = mean(B, axis=0)

    # subtract mean
    Am = A - tile(centroid_A, (num_rows, 1))
    Bm = B - tile(centroid_B, (num_rows, 1))

    # dot is matrix multiplication for array
    H = transpose(Am) * Bm

    # find rotation
    U, S, Vt = linalg.svd(H)
    R = Vt.T * U.T

    t = -centroid_A*R + centroid_B

    return R, t

# Test with random data

# Random rotation and translation
R = mat(random.rand(2,2))
t = mat(random.rand(1,2))

# make R a proper rotation matrix, force orthonormal
U, S, Vt = linalg.svd(R)
R = U*Vt


# number of points
n = 10

A = mat(random.rand(n,2));
B = A*R + tile(t, (n,1))

# Recover R and t
ret_R, ret_t = rigid_transform_3D(A, B)

# Compare the recovered R and t with the original
B2 = (A*ret_R) + tile(ret_t, (n,1))

# Find the root mean squared error
err = B2 - B
err = multiply(err, err)
err = sum(err)
rmse = sqrt(err/n);

print("Points A")
print(A)
print("")

print("Points B")
print(B)
print("")

print("Ground truth rotation")
print(R)

print("Recovered rotation")
print(ret_R)
print("")

print("Ground truth translation")
print(t)

print("Recovered translation")
print(ret_t)
print("")

print("RMSE:", rmse)

if rmse < 1e-5:
    print("Everything looks good!\n");
else:
    print("Hmm something doesn't look right ...\n");

Points A
[[0.31636423 0.44132698]
 [0.51109856 0.8146016 ]
 [0.28690292 0.14065618]
 [0.52056201 0.74541812]
 [0.82005599 0.85896947]
 [0.79329067 0.63082681]
 [0.34494983 0.04879719]
 [0.70019499 0.16848829]
 [0.23759181 0.08715586]
 [0.21653567 0.4047954 ]]

Points B
[[1.13013417 0.65663845]
 [1.50363222 0.85094389]
 [0.82942973 0.62752252]
 [1.43445966 0.8604868 ]
 [1.54835495 1.15985015]
 [1.32018169 1.13334691]
 [0.73763747 0.6856749 ]
 [0.85773654 1.04078234]
 [0.7758728  0.57827289]
 [1.09348794 0.55685191]]

Ground truth rotation
[[ 0.00114864  0.99999934]
 [ 0.99999934 -0.00114864]]
Recovered rotation
[[ 0.00114864  0.99999934]
 [ 0.99999934 -0.00114864]]

Ground truth translation
[[0.68844409 0.34078135]]
Recovered translation
[[0.68844409 0.34078135]]

RMSE: 4.018332571321416e-16
Everything looks good!



In [22]:
R

matrix([[ 0.00114864,  0.99999934],
        [ 0.99999934, -0.00114864]])